const cardsNamesDirectory = {
  animal: [
    ['bear', 'медведь'],
    ['cat', 'кот'],
    ['cow', 'корова'],
    ['dog', 'собака'],
    ['fox', 'лиса'],
    ['horse', 'лошадь'],
    ['rabbit', 'заяц'],
    ['tiger', 'тигр'],
  ],
  food: [
    ['apple', 'яблоко'],
    ['bread', 'хлеб'],
    ['cheese', 'сыр'],
    ['chocolate', 'шоколад'],
    ['coffee', 'кофе'],
    ['cookies', 'печенье'],
    ['ice-cream', 'мороженое'],
    ['tea', 'чай'],
  ],
  school: [
    ['board', 'доска'],
    ['book', 'книга'],
    ['lesson', 'урок'],
    ['pen', 'ручка'],
    ['pencil', 'карандаш'],
    ['pencil case', 'пенал'],
    ['pupil', 'ученик'],
    ['schoolbag', 'портфель'],
  ],
  action: [
    ['dance', 'танцевать'],
    ['jump', 'прыгать'],
    ['play', 'играть'],
    ['read', 'читать'],
    ['run', 'бежать'],
    ['sing', 'петь'],
    ['sleep', 'спать'],
    ['swim', 'плавать'],
  ],
  profession: [
    ['builder', 'строитель'],
    ['doctor', 'врач'],
    ['driver', 'водитель'],
    ['engineer', 'инженер'],
    ['policeman', 'милиционер'],
    ['seller', 'продавец'],
    ['spaceman', 'космонавт'],
    ['teacher', 'учитель'],
  ],
  nature: [
    ['cloud', 'облако'],
    ['flower', 'цветок'],
    ['forest', 'лес'],
    ['rain', 'дождь'],
    ['river', 'река'],
    ['sky', 'небо'],
    ['sun', 'солнце'],
    ['tree', 'дерево'],
  ],
  emotion: [
    ['angry', 'злой'],
    ['happy', 'счастливый'],
    ['offended', 'обиженный'],
    ['pensive', 'задумчивый'],
    ['sad', 'грустный'],
    ['smiling', 'улыбчивый'],
    ['surprised', 'удивленный'],
    ['tired', 'уставший'],
  ],
  clothes: [
    ['boots', 'ботинки'],
    ['dress', 'платье'],
    ['hat', 'шапка'],
    ['jacket', 'куртка'],
    ['pants', 'брюки'],
    ['shirt', 'рубашка'],
    ['skirt', 'юбка'],
    ['socks', 'носки'],
  ],
};

export default cardsNamesDirectory;
