export default {
  200: {
    name: 'thunderstorm,rain',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  201: {
    name: 'thunderstorm,rain',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  202: {
    name: 'thunderstorm,rain',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  210: {
    name: 'thunderstorm',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  211: {
    name: 'thunderstorm',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  212: {
    name: 'thunderstorm',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  221: {
    name: 'thunderstorm',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  230: {
    name: 'thunderstorm,drizzle',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  231: {
    name: 'thunderstorm,drizzle',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  232: {
    name: 'thunderstorm,drizzle',
    morning: './assets/img/thunder.svg',
    day: './assets/img/thunder.svg',
    evening: './assets/img/thunder.svg',
    night: './assets/img/thunder.svg',
  },
  300: {
    name: 'drizzle',
    morning: './assets/img/rainy-2.svg',
    day: './assets/img/rainy-2.svg',
    evening: './assets/img/rainy-4.svg',
    night: './assets/img/rainy-4.svg',
  },
  301: {
    name: 'drizzle',
    morning: './assets/img/rainy-3.svg',
    day: './assets/img/rainy-3.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  302: {
    name: 'drizzle',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  310: {
    name: 'drizzle',
    morning: './assets/img/rainy-1.svg',
    day: './assets/img/rainy-1.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  311: {
    name: 'drizzle',
    morning: './assets/img/rainy-3.svg',
    day: './assets/img/rainy-3.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  312: {
    name: 'drizzle',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  313: {
    name: 'rain',
    morning: './assets/img/rainy-1.svg',
    day: './assets/img/rainy-1.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  314: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  321: {
    name: 'drizzle',
    morning: './assets/img/rainy-3.svg',
    day: './assets/img/rainy-3.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  500: {
    name: 'rain',
    morning: './assets/img/rainy-1.svg',
    day: './assets/img/rainy-1.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  501: {
    name: 'rain',
    morning: './assets/img/rainy-3.svg',
    day: './assets/img/rainy-3.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  502: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  503: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  504: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  511: {
    name: 'hail',
    morning: './assets/img/rainy-7.svg',
    day: './assets/img/rainy-7.svg',
    evening: './assets/img/rainy-7.svg',
    night: './assets/img/rainy-7.svg',
  },
  520: {
    name: 'rain',
    morning: './assets/img/rainy-1.svg',
    day: './assets/img/rainy-1.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  521: {
    name: 'rain',
    morning: './assets/img/rainy-2.svg',
    day: './assets/img/rainy-2.svg',
    evening: './assets/img/rainy-4.svg',
    night: './assets/img/rainy-4.svg',
  },
  522: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  531: {
    name: 'rain',
    morning: './assets/img/rainy-6.svg',
    day: './assets/img/rainy-6.svg',
    evening: './assets/img/rainy-6.svg',
    night: './assets/img/rainy-6.svg',
  },
  600: {
    name: 'snow',
    morning: './assets/img/snowy-1.svg',
    day: './assets/img/snowy-1.svg',
    evening: './assets/img/snowy-4.svg',
    night: './assets/img/snowy-4.svg',
  },
  601: {
    name: 'snow',
    morning: './assets/img/snowy-2.svg',
    day: './assets/img/snowy-2.svg',
    evening: './assets/img/snowy-5.svg',
    night: './assets/img/snowy-5.svg',
  },
  602: {
    name: 'snow',
    evening: './assets/img/snowy-6.svg',
    day: './assets/img/snowy-6.svg',
    morning: './assets/img/snowy-6.svg',
    night: './assets/img/snowy-6.svg',
  },
  611: {
    name: 'sleet',
    morning: './assets/img/rainy-7.svg',
    day: './assets/img/rainy-7.svg',
    evening: './assets/img/rainy-7.svg',
    night: './assets/img/rainy-7.svg',
  },
  612: {
    name: 'sleet',
    morning: './assets/img/rainy-7.svg',
    day: './assets/img/rainy-7.svg',
    evening: './assets/img/rainy-7.svg',
    night: './assets/img/rainy-7.svg',
  },
  613: {
    name: 'sleet',
    morning: './assets/img/rainy-7.svg',
    day: './assets/img/rainy-7.svg',
    evening: './assets/img/rainy-7.svg',
    night: './assets/img/rainy-7.svg',
  },
  615: {
    name: 'drizzle',
    morning: './assets/img/rainy-1.svg',
    day: './assets/img/rainy-1.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  616: {
    name: 'drizzle',
    morning: './assets/img/rainy-3.svg',
    day: './assets/img/rainy-3.svg',
    evening: './assets/img/rainy-5.svg',
    night: './assets/img/rainy-5.svg',
  },
  620: {
    name: 'snow',
    morning: './assets/img/snowy-1.svg',
    day: './assets/img/snowy-1.svg',
    evening: './assets/img/snowy-4.svg',
    night: './assets/img/snowy-4.svg',
  },
  621: {
    name: 'snow',
    morning: './assets/img/snowy-2.svg',
    day: './assets/img/snowy-2.svg',
    evening: './assets/img/snowy-5.svg',
    night: './assets/img/snowy-5.svg',
  },
  622: {
    name: 'snow',
    morning: './assets/img/snowy-6.svg',
    day: './assets/img/snowy-6.svg',
    evening: './assets/img/snowy-6.svg',
    night: './assets/img/snowy-6.svg',
  },
  701: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  711: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  721: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  731: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  741: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  751: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  761: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  762: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  771: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  781: {
    name: 'fog',
    morning: './assets/img/cloudy-day-1.svg',
    day: './assets/img/cloudy-day-1.svg',
    evening: './assets/img/cloudy-night-1.svg',
    night: './assets/img/cloudy-night-1.svg',
  },
  800: {
    name: 'sky',
    morning: './assets/img/day.svg',
    day: './assets/img/day.svg',
    evening: './assets/img/night.svg',
    night: './assets/img/night.svg',
  },
  801: {
    name: 'clouds',
    morning: './assets/img/cloudy-day-2.svg',
    day: './assets/img/cloudy-day-2.svg',
    evening: './assets/img/cloudy-night-2.svg',
    night: './assets/img/cloudy-night-2.svg',
  },
  802: {
    name: 'cloudy',
    morning: './assets/img/cloudy-day-3.svg',
    day: './assets/img/cloudy-day-3.svg',
    evening: './assets/img/cloudy-night-3.svg',
    night: './assets/img/cloudy-night-3.svg',
  },
  803: {
    name: 'overcast',
    morning: './assets/img/cloudy.svg',
    day: './assets/img/cloudy.svg',
    evening: './assets/img/cloudy.svg',
    night: './assets/img/cloudy.svg',
  },
  804: {
    name: 'overcast',
    morning: './assets/img/cloudy.svg',
    day: './assets/img/cloudy.svg',
    evening: './assets/img/cloudy.svg',
    night: './assets/img/cloudy.svg',
  },
};
